/**
 * Stands in for every @material/web element module.
 *
 * md.jsx imports these classes and passes each to createComponent as
 * `elementClass`; the lit-react stub ignores that argument, so an inert class
 * is enough. They are listed explicitly because ESM named imports cannot be
 * served by a Proxy — if md.jsx starts importing another element, this file is
 * regenerated by test/stubs/regen.mjs rather than edited by hand.
 */
class StubElement {}

export const MdChipSet = StubElement;
export const MdDialog = StubElement;
export const MdFilledButton = StubElement;
export const MdFilledTonalButton = StubElement;
export const MdFilterChip = StubElement;
export const MdIconButton = StubElement;
export const MdOutlinedButton = StubElement;
export const MdOutlinedSelect = StubElement;
export const MdOutlinedTextField = StubElement;
export const MdSecondaryTab = StubElement;
export const MdSelectOption = StubElement;
export const MdSwitch = StubElement;
export const MdTabs = StubElement;
export const MdTextButton = StubElement;
export default StubElement;
