export function exportToCSV(rows, filename) {
  if(!rows || rows.length === 0) { alert('No data to export.'); return; }
  const headers = Object.keys(rows[0]);
  const csv = [
    headers.join(','),
    ...rows.map(row => headers.map(h => {
      const val = row[h] === null || row[h] === undefined ? '' : String(row[h]);
      return val.includes(',') || val.includes('"') || val.includes('\n')
        ? `"${val.replace(/"/g, '""')}"` : val;
    }).join(','))
  ].join('\n');
  const blob = new Blob([csv], {type:'text/csv;charset=utf-8;'});
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}

export function exportSummaryToMD(institute, summaryRows, selectedFYs) {
  const fyLabel = selectedFYs.length > 0 ? selectedFYs.join(', ') : 'All Fiscal Years';
  const date = new Date().toLocaleDateString('en-NP');
  const lines = [];
  lines.push(`# Training Summary — ${institute.name}`);
  if (institute.acronym) lines.push(`**Acronym:** ${institute.acronym}`);
  lines.push(`**Fiscal Years:** ${fyLabel}  `);
  lines.push(`**Generated:** ${date}`);
  lines.push('');
  lines.push('| Occupation | Level | Clients | Trainees | Districts | ST App/Pass | NSTB App/Pass | Affiliation |');
  lines.push('|---|---|---|---|---|---|---|---|');
  summaryRows.forEach(r => {
    const clients = [...(r.clientNames||[])].join(', ') || '—';
    const st = r.stAppeared ? `${r.stAppeared}/${r.stPass}` : '—';
    const nstb = r.nstbAppeared ? `${r.nstbAppeared}/${r.nstbPass}` : '—';
    const aff = r.affiliationStatus && r.affiliationStatus !== '—' ? r.affiliationStatus : '—';
    lines.push(`| ${r.occupation} | ${r.level||'—'} | ${clients} | ${r.trainees} | ${r.districts?.size||0} | ${st} | ${nstb} | ${aff} |`);
  });
  const total = summaryRows.reduce((a,r)=>({t:a.t+r.trainees,d:new Set([...a.d,...r.districts])}),{t:0,d:new Set()});
  lines.push(`| **TOTAL (${summaryRows.length} occupations)** | | | **${total.t}** | **${total.d.size}** | | | |`);
  lines.push('');
  lines.push(`*Generated by TVETtrack — Nepal TVET Registry*`);

  const blob = new Blob([lines.join('\n')], {type:'text/markdown'});
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `TVETtrack_${institute.acronym||institute.name.split(' ')[0]}_${selectedFYs.join('_')||'AllFYs'}.md`;
  a.click();
}

export function exportSummaryToPDF(institute, summaryRows, selectedFYs) {
  const fyLabel = selectedFYs.length > 0 ? selectedFYs.join(', ') : 'All Fiscal Years';
  const date = new Date().toLocaleDateString('en-NP');
  const total = summaryRows.reduce((a,r)=>({t:a.t+r.trainees,d:new Set([...a.d,...r.districts])}),{t:0,d:new Set()});

  const rows = summaryRows.map(r => `
    <tr>
      <td><strong>${r.occupation}</strong><br><small style="color:#666">${r.sector||''}</small></td>
      <td>${r.level||'—'}</td>
      <td style="font-size:11px">${[...(r.clientNames||[])].map(n=>`<span style="background:#ede9fe;color:#5b21b6;border-radius:3px;padding:1px 5px;margin:1px;display:inline-block">${n}</span>`).join(' ')}</td>
      <td style="text-align:right;font-weight:600">${r.trainees.toLocaleString()}</td>
      <td style="text-align:right">${r.districts?.size||0}</td>
      <td style="text-align:right">${r.stAppeared?`${r.stAppeared}/${r.stPass}`:'—'}</td>
      <td style="text-align:right">${r.nstbAppeared?`${r.nstbAppeared}/${r.nstbPass}`:'—'}</td>
      <td>${r.affiliationStatus&&r.affiliationStatus!=='—'?`<span style="background:#d1fae5;color:#065f46;border-radius:3px;padding:1px 5px">${r.affiliationStatus}</span>`:'—'}</td>
    </tr>`).join('');

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8">
  <title>TVETtrack Summary — ${institute.name}</title>
  <style>
    body{font-family:Arial,sans-serif;font-size:12px;color:#111;margin:24px}
    h1{font-size:18px;margin-bottom:4px}
    .meta{color:#555;font-size:11px;margin-bottom:16px}
    table{border-collapse:collapse;width:100%}
    th{background:#1e293b;color:#fff;padding:6px 8px;text-align:left;font-size:11px}
    td{padding:5px 8px;border-bottom:1px solid #e2e8f0;vertical-align:top}
    tr:nth-child(even) td{background:#f8fafc}
    .total td{background:#1e293b;color:#fff;font-weight:700}
    @media print{body{margin:0}}
  </style></head><body>
  <h1>Training Summary — ${institute.name}${institute.acronym?` (${institute.acronym})`:''}</h1>
  <div class="meta">Fiscal Years: ${fyLabel} &nbsp;|&nbsp; Generated: ${date} &nbsp;|&nbsp; TVETtrack — Nepal TVET Registry</div>
  <table>
    <thead><tr>
      <th>Occupation</th><th>Level</th><th>Clients</th>
      <th style="text-align:right">Trainees</th><th style="text-align:right">Districts</th>
      <th style="text-align:right">ST App/Pass</th><th style="text-align:right">NSTB App/Pass</th>
      <th>Affiliation</th>
    </tr></thead>
    <tbody>${rows}</tbody>
    <tfoot><tr class="total">
      <td colspan="2">TOTAL (${summaryRows.length} occupations)</td>
      <td></td>
      <td style="text-align:right">${total.t.toLocaleString()}</td>
      <td style="text-align:right">${total.d.size}</td>
      <td colspan="3"></td>
    </tr></tfoot>
  </table>
  </body></html>`;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.onload = () => win.print();
}

export function exportSummaryToCSV(institute, summaryRows, selectedFYs) {
  const fyLabel = selectedFYs.length > 0 ? selectedFYs.join('_') : 'AllFYs';
  const rows = summaryRows.map(r => ({
    'Institute': institute.name,
    'Acronym': institute.acronym || '',
    'Occupation': r.occupation,
    'Level': r.level || '—',
    'Sector': r.sector,
    'NSTB Level': r.nstbLevel,
    'Fiscal Years': selectedFYs.join(', ') || 'All',
    'Unique Clients': r.clientIds?.size || 0,
    'Client Names': [...(r.clientNames || [])].join('; '),
    'Total Trainees': r.trainees,
    'Districts': [...(r.districts || [])].join('; '),
    'No. of Districts': r.districts?.size || 0,
    'ST Appeared (Client)': r.stAppeared || '',
    'ST Pass (Client)': r.stPass || '',
    'Employment %': r.employmentActual || '',
    'NSTB Applied': r.nstbApplied || '',
    'NSTB Appeared': r.nstbAppeared || '',
    'NSTB Pass': r.nstbPass || '',
    'NSTB Pass Rate %': r.nstbAppeared ? ((r.nstbPass/r.nstbAppeared)*100).toFixed(1) : '',
    'NSTB Appear Rate %': r.nstbApplied ? ((r.nstbAppeared/r.nstbApplied)*100).toFixed(1) : '',
    'Affiliation Status': r.affiliationStatus,
    'Affiliation Valid From': r.affiliationFrom,
    'Affiliation Valid To': r.affiliationTo,
  }));
  exportToCSV(rows, `TVETtrack_${institute.acronym || institute.name.split(' ')[0]}_${fyLabel}.csv`);
}

export function exportComparisonToCSV(institutes, selectedFYs) {
  const rows = [];
  institutes.forEach(inst => {
    inst.nstb.filter(n => selectedFYs.length === 0 || selectedFYs.includes(n.fy)).forEach(n => {
      rows.push({
        'Institute': inst.name,
        'Acronym': inst.acronym || '',
        'Status': inst.status,
        'Fiscal Year': n.fy,
        'Occupation': n.occupation,
        'Level': n.level,
        'Applied': n.applied,
        'Appeared': n.appeared,
        'Pass': n.pass,
        'Appear Rate %': n.applied ? ((n.appeared/n.applied)*100).toFixed(1) : '',
        'Pass Rate %': n.appeared ? ((n.pass/n.appeared)*100).toFixed(1) : '',
      });
    });
  });
  const fyLabel = selectedFYs.length > 0 ? selectedFYs.join('_') : 'AllFYs';
  exportToCSV(rows, `TVETtrack_Comparison_${fyLabel}.csv`);
}
